In [2]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
from _src import SimpleDistributor

In [4]:
file_path = "data/apt_1.xlsx"

simple_dist = SimpleDistributor(file_path=file_path)

In [8]:
simple_dist.set_init()
simple_dist.select_month(1)

In [9]:
simple_dist.meter_year

,아파트1-104-1206,아파트1-104-303,아파트1-104-1307,아파트1-104-1208,아파트1-104-408,아파트1-104-203,아파트1-103-1402,아파트1-103-402,아파트1-103-1201,아파트1-103-801,...,아파트1-102-901,아파트1-103-1905,아파트1-103-503,아파트1-103-1504,아파트1-103-606,아파트1-103-903,아파트1-103-1106,아파트1-103-705,아파트1-103-1505,아파트1-103-406
1,99,10,23,40,39,197,218,228,84,223,...,202,329,327,300,415,273,255,228,384,317
2,94,77,18,135,30,192,201,230,154,188,...,198,307,231,270,399,256,237,211,309,290
3,96,77,20,169,28,216,231,241,247,232,...,238,293,283,284,421,265,248,235,314,308
4,75,76,30,127,58,217,226,232,250,209,...,202,294,238,231,401,267,202,214,309,304
5,165,150,161,7,75,164,216,224,200,189,...,206,276,286,242,398,260,205,187,319,292
6,186,148,108,6,48,182,211,225,192,192,...,171,269,294,255,393,269,184,182,325,238
7,292,136,273,6,52,247,375,306,253,287,...,199,355,305,278,491,343,336,298,543,373
8,311,7,240,6,49,318,390,345,271,319,...,184,387,292,284,562,345,392,409,568,449
9,173,7,98,6,41,231,214,239,183,193,...,160,273,253,232,361,277,179,192,314,230
10,149,7,30,8,35,200,202,209,193,224,...,182,276,285,238,374,249,171,209,318,299
11,21,2,0,7,17,197,209,178,190,210,...,201,316,300,255,381,251,197,199,321,273
12,21,2,24,16,41,178,232,190,186,218,...,212,334,337,284,429,274,260,201,331,322

In [10]:
simple_dist.meter_month

              name usage (kWh)
0    아파트1-104-1206          99
1     아파트1-104-303          10
2    아파트1-104-1307          23
3    아파트1-104-1208          40
4     아파트1-104-408          39
..             ...         ...
103   아파트1-103-903         273
104  아파트1-103-1106         255
105   아파트1-103-705         228
106  아파트1-103-1505         384
107   아파트1-103-406         317

[108 rows x 2 columns]

In [21]:
simple_dist.set_cont()

In [23]:
simple_dist.set_calc(public_percentage=30)

In [31]:
self = simple_dist

apt = self.calc.apt_obj

apt.basic * 108

654480

In [32]:
apt.basic * 108 * self.cont_

array([2083.125, 210.41666666666666, 483.9583333333333, 841.6666666666666,
       820.625, 4145.208333333333, 4587.083333333333, 4797.5, 1767.5,
       4692.291666666667, 4965.833333333333, 8143.125, 4671.25,
       8353.541666666666, 6712.291666666666, 14960.625, 5281.458333333334,
       6859.583333333334, 5365.625, 5407.708333333333, 8921.666666666666,
       3282.5, 4797.5, 7364.583333333334, 5323.541666666667,
       5028.958333333333, 2714.375, 7259.375, 7911.666666666667,
       5007.916666666667, 7995.833333333333, 5618.125, 4608.125, 3850.625,
       6249.375000000001, 9952.708333333332, 6775.416666666666,
       6501.875000000001, 8753.333333333334, 5512.916666666667,
       5996.875000000001, 5050.0, 4986.875, 8542.916666666666,
       5891.666666666667, 6123.125, 8122.083333333334, 4902.708333333333,
       6964.791666666666, 4671.25, 5975.833333333333, 8521.875, 8837.5,
       5344.583333333333, 7175.208333333333, 5407.708333333333,
       3556.041666666667, 4502.916666666667, 6270.416666666666, 7385.625,
       8016.875, 5533.958333333334, 10478.750000000002, 7806.458333333334,
       7764.375, 7806.458333333334, 4502.916666666667, 2335.625,
       3871.6666666666665, 3114.1666666666665, 3177.2916666666665,
       3808.541666666667, 6102.083333333333, 3787.5, 420.8333333333333,
       3703.3333333333335, 4629.166666666667, 6480.833333333333,
       3808.541666666667, 4271.458333333333, 10394.583333333332,
       9174.166666666666, 5555.0, 5891.666666666667, 9742.291666666668,
       6817.5, 9573.958333333334, 6649.166666666667, 7385.625,
       8879.583333333334, 8122.083333333334, 6522.916666666666,
       8185.208333333333, 7217.291666666666, 14497.708333333332,
       5597.083333333333, 8143.125, 8143.125, 4250.416666666667,
       6922.708333333333, 6880.625, 6312.5, 8732.291666666668,
       5744.375000000001, 5365.625, 4797.5, 8080.0, 6670.208333333333],
      dtype=object)

In [33]:
apt.elec_rate * 108 * self.cont_

array([15618.625, 1577.638888888889, 3628.5694444444443,
       6310.555555555556, 6152.791666666666, 31079.48611111111,
       34392.52777777778, 35970.166666666664, 13252.166666666666,
       35181.347222222226, 37232.27777777778, 61054.625,
       35023.58333333333, 62632.26388888889, 50326.680555555555,
       112170.125, 39598.73611111112, 51431.02777777778,
       40229.791666666664, 40545.319444444445, 66891.88888888889,
       24611.166666666664, 35970.166666666664, 55217.36111111112,
       39914.26388888889, 37705.569444444445, 20351.541666666668,
       54428.54166666667, 59319.222222222226, 37547.805555555555,
       59950.277777777774, 42122.958333333336, 34550.291666666664,
       28870.791666666668, 46855.87500000001, 74622.31944444444,
       50799.97222222222, 48749.04166666667, 65629.77777777778,
       41334.13888888889, 44962.708333333336, 37863.33333333333,
       37390.041666666664, 64052.13888888888, 44173.88888888889,
       45909.291666666664, 60896.86111111112, 36758.98611111111,
       52219.84722222222, 35023.58333333333, 44804.944444444445,
       63894.375, 66260.83333333333, 40072.027777777774,
       53797.48611111111, 40545.319444444445, 26662.097222222223,
       33761.47222222222, 47013.63888888889, 55375.125, 60108.04166666667,
       41491.90277777778, 78566.41666666667, 58530.40277777778, 58214.875,
       58530.40277777778, 33761.47222222222, 17511.791666666664,
       29028.555555555555, 23349.055555555555, 23822.34722222222,
       28555.26388888889, 45751.527777777774, 28397.5, 3155.277777777778,
       27766.444444444445, 34708.055555555555, 48591.27777777778,
       28555.26388888889, 32026.06944444444, 77935.36111111111,
       68785.05555555556, 41649.666666666664, 44173.88888888889,
       73044.68055555556, 51115.5, 71782.56944444445, 49853.38888888889,
       55375.125, 66576.36111111111, 60896.86111111112,
       48906.805555555555, 61370.152777777774, 54113.01388888888,
       108699.31944444444, 41965.19444444444, 61054.625, 61054.625,
       31868.305555555555, 51904.319444444445, 51588.791666666664,
       47329.166666666664, 65472.01388888889, 43069.54166666667,
       40229.791666666664, 35970.166666666664, 60581.33333333333,
       50011.152777777774], dtype=object)

In [38]:
self.set_bill_table(public_percentage=30)

In [39]:
bill_table = self.bill_table.get

In [49]:
bill_table

            기본요금    전력량요금  기후환경요금  연료비조정액   부가가치세  전력산업기반기금   최종청구금액
APT       654480  4907088  235224 -133164  566352    209520  6438960
세대부       197480  3118820  164805  -93312  334205    123150  3798980
공용부       457000  1788268   70419  -39852  232147     86370  2594352
실제 공용부 값       0        0       0       0       0         0  2639980
오차             0        0       0       0       0         0    45628

In [48]:
public_wons = bill_table.loc['공용부'][['기본요금', '전력량요금']].values

public_wons

array([ 457000, 1788268])

In [46]:
public_wons[0] * self.cont_

array([1454.5717592592591, 146.9264403292181, 337.93081275720164,
       587.7057613168724, 573.0131172839506, 2894.4508744855966,
       3202.996399176955, 3349.9228395061727, 1234.182098765432,
       3276.459619341564, 3467.463991769547, 5686.053240740741,
       3261.7669753086416, 5832.979681069959, 4686.953446502057,
       10446.469907407407, 3687.853652263375, 4789.80195473251,
       3746.624228395062, 3776.009516460905, 6229.681069958848,
       2292.0524691358023, 3349.9228395061727, 5142.425411522634,
       3717.238940329218, 3511.5419238683126, 1895.3510802469136,
       5068.962191358025, 5524.434156378601, 3496.849279835391,
       5583.204732510288, 3922.9359567901233, 3217.6890432098767,
       2688.7538580246915, 4363.715277777778, 6949.620627572016,
       4731.031378600823, 4540.02700617284, 6112.139917695473,
       3849.4727366255142, 4187.403549382717, 3526.234567901234,
       3482.1566358024693, 5965.213477366255, 4113.940329218107,
       4275.559413580247, 5671.360596707819, 3423.386059670782,
       4863.265174897119, 3261.7669753086416, 4172.710905349794,
       5950.520833333334, 6170.91049382716, 3731.93158436214,
       5010.1916152263375, 3776.009516460905, 2483.0568415637863,
       3144.2258230452676, 4378.4079218107, 5157.118055555556,
       5597.89737654321, 3864.1653806584363, 7316.936728395062,
       5450.970936213992, 5421.585648148149, 5450.970936213992,
       3144.2258230452676, 1630.8834876543208, 2703.446502057613,
       2174.511316872428, 2218.5892489711932, 2659.3685699588477,
       4260.866769547325, 2644.6759259259256, 293.8528806584362,
       2585.9053497942386, 3232.3816872427983, 4525.334362139918,
       2659.3685699588477, 2982.6067386831273, 7258.166152263374,
       6405.99279835391, 3878.858024691358, 4113.940329218107,
       6802.694187242799, 4760.416666666666, 6685.153034979424,
       4642.875514403292, 5157.118055555556, 6200.2957818930045,
       5671.360596707819, 4554.719650205761, 5715.438528806584,
       5039.576903292181, 10123.231738683127, 3908.2433127572012,
       5686.053240740741, 5686.053240740741, 2967.9140946502057,
       4833.879886831275, 4804.494598765432, 4407.793209876543,
       6097.447273662552, 4011.0918209876545, 3746.624228395062,
       3349.9228395061727, 5641.975308641975, 4657.568158436214],
      dtype=object)

In [47]:
public_wons[1] * self.cont_

array([5691.825231481481, 574.9318415637861, 1322.3432355967077,
       2299.7273662551443, 2242.2341820987654, 11326.157278806584,
       12533.514146090536, 13108.44598765432, 4829.427469135802,
       12820.98006687243, 13568.39146090535, 22249.86226851852,
       12763.486882716048, 22824.794110082305, 18340.325745884773,
       40877.65393518519, 14430.78922325103, 18742.778034979427,
       14660.761959876543, 14775.7483281893, 24377.110082304527,
       8968.936728395061, 13108.44598765432, 20122.614454732513,
       14545.775591563786, 13740.871013374484, 7416.62075617284,
       19835.148533950618, 21617.437242798354, 13683.377829218107,
       21847.40997942387, 15350.680169753086, 12591.007330246914,
       10521.252700617284, 17075.475694444445, 27194.276105967077,
       18512.80529835391, 17765.39390432099, 23917.164609053496,
       15063.214248971193, 16385.557484567904, 13798.364197530864,
       13625.88464506173, 23342.23276748971, 16098.091563786009,
       16730.516589506173, 22192.36908436214, 13395.911908436214,
       19030.243955761314, 12763.486882716048, 16328.064300411523,
       23284.739583333336, 24147.13734567901, 14603.268775720164,
       19605.1757973251, 14775.7483281893, 9716.348122427984,
       12303.54140946502, 17132.968878600823, 20180.107638888887,
       21904.90316358025, 15120.707433127573, 28631.605709876545,
       21329.971322016463, 21214.984953703704, 21329.971322016463,
       12303.54140946502, 6381.743441358024, 10578.745884773662,
       8508.991255144034, 8681.470807613168, 10406.266332304527,
       16673.02340534979, 10348.773148148148, 1149.8636831275721,
       10118.800411522634, 12648.500514403291, 17707.90072016461,
       10406.266332304527, 11671.116383744855, 28401.632973251028,
       25067.028292181072, 15178.20061728395, 16098.091563786009,
       26619.344264403295, 18627.791666666664, 26159.398791152264,
       18167.84619341564, 20180.107638888887, 24262.123713991772,
       22192.36908436214, 17822.887088477364, 22364.848636831273,
       19720.16216563786, 39612.803883744855, 15293.186985596707,
       22249.86226851852, 22249.86226851852, 11613.623199588477,
       18915.25758744856, 18800.2712191358, 17247.955246913578,
       23859.671424897122, 15695.639274691359, 14660.761959876543,
       13108.44598765432, 22077.382716049382, 18225.339377572014],
      dtype=object)